services:
  db:
    image: mysql
    container_name: bd1_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proyecto-final
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
